# Generated by Django 5.2.7 on 2026-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('critical', 'Критичний')], default='medium', max_length=50),
        ),
    ]
