# Generated by Django 5.2.7 on 2026-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_thumbnail'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('building', 'place_name'), name='unique_building_place_name'),
        ),
    ]
