# Generated by Django 5.2.7 on 2026-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
