# Generated by Django 5.2.7 on 2026-07-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_userprofile_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='photo_after',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos_after/'),
        ),
    ]
