# Generated by Django 5.2.7 on 2026-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_photo_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_status', models.CharField(default='stable', max_length=20)),
                ('electricity_status', models.CharField(default='stable', max_length=20)),
                ('heating_status', models.CharField(default='stable', max_length=20)),
                ('internet_status', models.CharField(default='stable', max_length=20)),
                ('elevators_status', models.CharField(default='stable', max_length=20)),
                ('announcement_title', models.CharField(blank=True, default='', max_length=200)),
                ('announcement_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campus_status',
            },
        ),
    ]
