# Generated by Django 5.2.7 on 2026-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_campusstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusstatus',
            name='security_status',
            field=models.CharField(default='stable', max_length=20),
        ),
    ]
