# Generated by Django 5.2.7 on 2026-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_announcement_remove_campusstatus_security_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitorybuilding',
            name='commandant_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
