# Generated by Django 5.2.7 on 2026-07-10 20:54

import complaints.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_dormitorybuilding_commandant_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default=complaints.models.generate_invite_token, max_length=255, unique=True)),
                ('role_name', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to='complaints.userprofile')),
            ],
            options={
                'db_table': 'registration_invite',
                'ordering': ['-created_at'],
            },
        ),
    ]
