# Generated by Django 5.2.7 on 2026-07-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_registrationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
